name: Push to dockerhub

on:
  push:
    branches:
      - feat/upgrade

jobs:
  push_to_dockerhub:
    name: Push to dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setting Qemu
        uses: docker/setup-qemu-action@v2

      - name: Setting docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Build and push to dockerhub
        id: build-and-push
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: true
          platforms: linux/amd64, linux/arm64
          tags: isenganime/drone-rsync
          labels: ${{ steps.meta.outputs.label }}
